export function handleException(status) {
  console.log("Error: ", status);
}
